/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function graphqxlToSdl(vfs: object, entryPath: string, indentSpaces?: number | undefined | null, privatePrefix?: string | undefined | null): string
